name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          separator: ','
      - name: Build static Catalog
        run: |
          sudo apt install -y proj-bin libproj-dev
          pip install open-science-catalog-builder/
          osc build data/ -o dist/ \
            --root-href "https://eoepca.github.io/open-science-catalog-metadata-staging/" \
            --updated-files ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Copying Catalog client
        run: |
          cp -r client/* dist/
      # - name: Building Catalog client
      #   run: |
      #     cd stac-browser/
      #     npm install
      #     npm run build -- --catalogUrl="https://${GITHUB_REPOSITORY_OWNER}.github.io/$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')/catalog.json" --pathPrefix="/$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')/"
      #     cp -r dist/* ../dist
      #     cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
